# Generated by Django 4.1.2 on 2023-04-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_landingpage_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
