# Generated by Django 4.1.2 on 2023-04-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_feedback_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='img',
        ),
    ]
