# Generated by Django 4.1.2 on 2023-04-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_feedback_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='img',
        ),
    ]
